### PR TITLE
Made some changes to the navbar and added a new logo.

### PR DESCRIPTION
**Pull request by kunaljain0212**
I hope you like it! :)

### CODE REVIEW

**Comment by KushalBhanot** [comment]
Hey, @kunaljain0212!

Nice touch! But the changes you made are not responsive and the website looks inconsistent after it. Test the changes before making a PR. I don't mean to demotivate you. All I'm saying is making PRs that the maintainer can't refuse. I hope that you'll come up with the best PR possible :) 

Cheers,
Kushal

**Comment by kunaljain0212** [comment]
Sure, no issues! I will work on it and come up with a better solution. :)

**Comment by kunaljain0212** [comment]
@KushalBhanot I fixed the responsive issue. Now the navbar doesn't cover the content in mobile devices. Could you please look into it?

**Comment by kunaljain0212** [comment]
@KushalBhanot this PR is ready for review. Could you please look into it :)

**Comment by KushalBhanot** [comment]
The changes you made are very inconsistent with the website. Also, try making contributions to some other projects and not my portfolio.

**Pull request closed without merging**
